services:
  db:
    image: postgres:15-alpine
    container_name: pos-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pos_db
    ports:
      - "5433:5432"
    volumes:
      - pos_db_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: pos-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:admin@db:5432/pos_db"
      JWT_SECRET: "7d696b5587a34bc54a832a6535ee466de7c9b8267174aa105adc355dfb5778d6eb153d9181a382db664278568f64159d5031ba534eeb466f803504af4c8a8bf7"
      FRONTEND_URL: "http://localhost:3001"
      PORT: 3000
    depends_on:
      - db

  adminer:
    image: adminer
    container_name: pos-adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pos_db_data:
